locallib.php
After editing activity in moodle, group name and description text will not be overwrite.
=> forbidden overwrite course name and desc

classes/client/client.php
Added "Accredible-Integration" to the request headers. This branch is based on https://github.com/accredible/moodle-mod_accredible/pull/24 which improves the error logging as well as the request logic.
=> Add Accredible-Integration to request headers

classes/Html2Text/Html2Text.php, classes/apiRest/apiRest.php, classes/client/client.php, classes/event/certificate_created.php, db/access.php, db/events.php, db/log.php, db/services.php, db/upgrade.php, index.php, lang/en/accredible.php, lang/en/error.php, lib.php, locallib.php, mod_form.php, settings.php, version.php, view.php
Using [Code-checker](https://moodle.org/plugins/local_codechecker) plugin, I formatted the code to follow the [Moodle coding style](https://docs.moodle.org/dev/Coding_style). As a result, the number of errors and warnings decreased from 2,783 to 750 and 330 to 146, respectively.
The remaining errors are mainly `Variable "xxx" must not contain underscores`. They can be solved by renaming variables and functions, but that is kind of dangerous. Therefore, I'd like to leave them for now and refactor them one by one when adding or updating features.
=> Refactor to follow the Moodle coding style

locallib.php
Fixed the errors and warnings from code-checker in locallib.php.
This has both NTGR-48 and NTGR-87 merged to it as it is dependant on both.
=> Fix/ntgr 47/coding style locallib

classes/client/client.php, tests/classes/client/client_test.php
Fixed the coding style of `client.php` and `client_test.php`.
=> Fix client.php coding style

mod_form.php
Fixed the errors and warnings from code-checker in mod_form.php.
=> fix all code-checker error and warnings in mod_form.php

classes/apirest/apirest.php
Fixed the errors and warnings from code-checker in classes/apirest.php.
=> fix all code-checker error and warnings in apirest.php

tests/locallib_test.php
Fixed the errors and warnings from code-checker in tests/locallib_test.php.
=> fix all code-checker error and warnings in locallib_test.php

view.php
Fixed the errors and warnings from code-checker in view.php.
=> fix all code-checker error and warnings in view.php

.github/workflows/moodle-ci.yml, locallib.php, tests/classes/apirest/apirest_test.php
Added [Moodle Plugin CI](https://moodlehq.github.io/moodle-plugin-ci/) with GitHub Actions.
The configuration is set up based on the public example [gha.dist.yml](https://moodlehq.github.io/moodle-plugin-ci/GHAFileExplained.html).
The help page to explain each step: https://moodlehq.github.io/moodle-plugin-ci/Help.html
=> Add GitHub Actions: Moodle Plugin CI

classes/apirest/apirest.php, tests/classes/apirest/apirest_test.php, tests/fixtures/mockapi/v1/credentials/recipient_sso_link_not_found.json, tests/fixtures/mockapi/v1/credentials/recipient_sso_link_success.json
Source: [NTGR-380](https://accredible.atlassian.net/browse/NTGR-380)
This PR add a change to send
the recipient email in lower case
when requesting the sso link
=> [NTGR-380] lowercase recipient email when requesting sso link

classes/Html2Text/Html2Text.php, classes/apirest/apirest.php, classes/client/client.php, classes/event/certificate_created.php, classes/local/credentials.php, classes/local/groups.php, db/upgrade.php, locallib.php, mod_form.php, tests/apirest/mod_accredible_apirest_test.php, tests/client/mod_accredible_client_test.php, tests/local/mod_accredible_credentials_test.php, tests/local/mod_accredible_groups_test.php, tests/mod_accredible_lib_test.php, tests/mod_accredible_locallib_test.php
Fix warnings from Moodle Code Checker after a major version upgrade
=> Fix code checker warnings

db/install.xml, db/upgrade.php
Source: [NTGR-291](https://accredible.atlassian.net/browse/NTGR-291)
=> (V2.2 1/3) Add grade attributes to accredible DB table

classes/local/credentials.php, locallib.php, version.php
PR to sync the develop branch with latest changes in the release.
=> Merge release branch to develop

.github/workflows/moodle-ci.yml, classes/local/users.php, lib.php, locallib.php, tests/mod_accredible_locallib_test.php
=> ACMS-4661 - Fix Moodle errors

.github/workflows/moodle-ci.yml, Dockerfile, README.md, docker-compose.yml, tests/apirest/mod_accredible_apirest_test.php, tests/client/mod_accredible_client_test.php, tests/local/mod_accredible_attribute_keys_test.php, tests/local/mod_accredible_credentials_test.php, tests/local/mod_accredible_evidenceitems_test.php, tests/local/mod_accredible_groups_test.php, tests/local/mod_accredible_users_test.php, tests/mod_accredible_lib_test.php, tests/mod_accredible_locallib_test.php
This PR;
- Updated the docker setup to work for both Intel and Apple chipsets
- Updated Moodle image to `4.0.11`
- Updated phpmyadmin to `bitnami/phpmyadmin` 
- Updated Moodle versions to be tested against in CI 
- Removed `MOODLE_39_STABLE`
- Added `MOODLE_400_STABLE`
- Added coverage (`@covers`, `@coversNothing`) annotation to unit tests to ensure no warnings are shown in CI leading to failures
=> DGR-544 - [Moodle] Docker setup + CI updates

classes/local/accredible.php, lib.php, tests/local/mod_accredible_accredible_test.php
This PR;
- Refactors `lib.php` to decouple DB operations for saving & updating `accredible` table
- Updates `accredible.php` to handle `attributemapping`
- Adds unit tests for `accredible.php`
=> DGR-262 [Moodle]- Update mod_form callback functions to handle attributemapping

classes/local/formhelper.php, lang/en/accredible.php, mod_form.php, tests/local/mod_accredible_formhelper_test.php
This PR adds the option Course Total to grade attribute mapping.
=> DGR-342: Add course grade option to attribute mapping

classes/local/accredible.php, lang/en/accredible.php, mod_form.php, tests/local/mod_accredible_accredible_test.php
This PR adds the input field of the final grade to pass to mod_form.
https://github.com/accredible/moodle-mod_accredible/assets/20009662/077c2d6c-5797-494c-9bb5-9b3e7bca70c8
=> DGR-257: Add final grade to pass input field to mod_form

backup/moodle2/backup_accredible_stepslib.php, classes/local/accredible.php, db/install.xml, db/upgrade.php, lang/en/accredible.php, mod_form.php, tests/local/mod_accredible_accredible_test.php, version.php
This PR removes finalgradetopass from the DB table and reverts the change on mod_form.
=> DGR-588: Revert finalgradetopass

.github/workflows/moodle-ci.yml, Dockerfile
This PR adds Moodle 4.5 to our workflow + updates the docker image to v4.5.4
=> DGR-2074 - Moodle plugin upgrade
